In [1]:
import numpy as np

In [2]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# 넘파이 배열의 크기 확인
data.shape

(2, 3)

In [4]:
# 원소들의 자료형 확인
data.dtype

dtype('int64')

In [5]:
arr = [[2,4,6],[7,8,9]]
arr

[[2, 4, 6], [7, 8, 9]]

In [6]:
to_np = np.array(arr)
to_np

array([[2, 4, 6],
       [7, 8, 9]])

In [7]:
zero_arr = np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [8]:
one_arr = np.ones([2,3])
one_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [11]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
data = np.array([[1, 2, 3], [4, 5, 6]])
one_arr = np.ones([2,3])
data + one_arr

array([[2., 3., 4.],
       [5., 6., 7.]])

In [13]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
data[3]

3

In [15]:
data[2:5]

array([2, 3, 4])

In [16]:
data[4:7] = 10
data

array([ 0,  1,  2,  3, 10, 10, 10,  7,  8,  9])

In [17]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
data.reshape([2,5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
data.reshape([5,2])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
data = np.arange(10)
data.sum()

45

In [21]:
data.mean()

4.5

In [22]:
data2 = data.reshape([2,5])
data2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
data2.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [24]:
data2.sum(axis=1)

array([10, 35])

In [25]:
data2.mean(axis=1)

array([2., 7.])